### ISSUE TITLE
compile error in simple example

### ISSUE THREAD

**Issue by krux02** [HPAC/TTC-C#4]
I have a compile error in a simple example that I've written, and I can't figure out what I did wrong, since the compilation problem doesn't really help me what went wrong.

this is the error I got during execution:

```
sTranspose_10_2x12_par.cpp(19): error: no instance of function template "sTranspose_10_2x12_par" matches the argument list
            argument types are: (const float *, float *, float, float, const int *, const int *)
      sTranspose_10_2x12_par<2, 3, 4>((const TENSOR_IN_T *)input,
      ^

icpc: error #10236: File not found:  'sTranspose_10_2x12_par.o'
icpc: command line error: no files specified; for help type "icpc -help"
```

The test program I've written to produce this bug is here: 
https://github.com/krux02/TTC-C-test/blob/master/main.c

when `LD_LIBRARY_PATH`, `LIBRARY_PATH` and `INCLUDE_PATH` are set correctly, `make && ./a.out` is enough to reproduce the bug.

**Comment by tongsucn** [comment]
Hi, sorry for the late reply. I just tried your test program and checked the debug log. I think your program should be equivalent to this TTC command:

`ttc --maxImplementations=10 --numThreads=24 --affinity=compact,1 --size=2,3,4 --perm=1,2,0 --beta=1.000000`

Is that correct? If so, I need talk to @springer13 . It seems that it's caused by TTC's runtime error. I will update this issue if any progress.

**Comment by springer13** [comment]
> |ttc --maxImplementations=10 --numThreads=24 --affinity=compact,1
> --size=2,3,4 --perm=1,2,0 --beta=1.000000|

Hm, but this command is working for me. So you say that exactly this
command is crashing for you?

**Comment by tongsucn** [comment]
@springer13  I think you are right. I didn't run it on the AVX-enabled cluster. The reason for this error is that the TTC combined two indices, but the TTC-C did not. I will fix this problem.

**Comment by krux02** [comment]
Any progress so far? Basically this example is my hello world for TTC-C and without it working I am completely blocked ot integrate TCC-C for my master theses.

**Comment by krux02** [comment]
Ok, I updated my example now to use the new version, but I still get errors:

```
  File "/home/ad095683/.local/bin/ttc", line 5, in <module>
    main()
  File "/home/ad095683/.local/lib/python2.7/site-packages/ttc/ttc.py", line 1370, in main
    generateTransposition( ttc_args )
  File "/home/ad095683/.local/lib/python2.7/site-packages/ttc/ttc.py", line 816, in generateTransposition
    traceback.print_stack()
```

I think it worked once, but then I could not repeat my result. every time I executed it afterwards just gave me that error which is not much helping at figuring out what is wrong.

**Comment by springer13** [comment]
are you sure that...: 1) ... you are have the latest version of TTC installed? It looks like your version is slightly out of date since line 1370 of ttc.py does not correspond to generateTransposition() any more. 2) ... you are executing the code on an AVX-enabled processor?

could you please delete your current ttc.db in your $TTC_ROOT directory and try again? If it works, please try twice, it might be that this error is related to the lookup of an existing solution.

**Comment by krux02** [comment]
ok, I updated now to the newest version of TTC. Now it works. I guess the problem is, that TTC-C is not locked to a specific version of TTC, I guess I make a new issue for this.
